name: Deploy to Production
on:
  push:
    branches:
      - main

jobs:
  deploy_to_production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Trigger Jenkins job
        run: |
          # Trigger Jenkins job here
